version: 2
project_name: aws-creds-tool
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./main.go
    binary: aws-creds-tool

archives:
  - format: tar.gz
    # Use standard archive names that are broadly compatible
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - id: aws-creds-tool-deb
    packager: deb
    formats:
      - deb
    name: aws-creds-tool
    license: MIT
    homepage: https://github.com/edgar-elian-rodriguez/aws-creds-tool
    description: "AWS Credential Administrator"
    maintainer: "edgar-elian-rodriguez"
    vendor: "edgar-elian-rodriguez"
    section: utils
    builds:
      - aws-creds-tool
  - id: aws-creds-tool-rpm
    packager: rpm
    formats:
      - rpm
    name: aws-creds-tool
    license: MIT
    homepage: https://github.com/edgar-elian-rodriguez/aws-creds-tool
    description: "AWS Credential Administrator"
    maintainer: "edgar-elian-rodriguez"
    vendor: "edgar-elian-rodriguez"
    builds:
      - aws-creds-tool

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
